// businessData.js
const businessData = [
  {
    id: 1,
    name: "Business 1",
    location: "Kolding",
    service: "Barber",
    imageUrl: "/barber.jpg",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Business 2",
    location: "Kolding",
    service: "Barber",
    imageUrl: "/barber.jpg",
    rating: 4.0,
  },
  {
    id: 3,
    name: "Business 3",
    location: "Kolding",
    service: "Salon",
    imageUrl: "/salon.jpg",
    rating: 3,
  },
  {
    id: 4,
    name: "Business 4",
    location: "Copenhagen",
    service: "Salon",
    imageUrl: "/salon.jpg",
    rating: 4.8,
  },
  {
    id: 5,
    name: "Business 5",
    location: "Aarhus",
    service: "Salon",
    imageUrl: "/salon.jpg",
    rating: 4.2,
  },
  {
    id: 6,
    name: "Business 6",
    location: "Aarhus",
    service: "Massage",
    imageUrl: "/spa.jpg",
    rating: 3.9,
  },
  {
    id: 7,
    name: "Business 7",
    location: "Aarhus",
    service: "Salon",
    imageUrl: "/salon.jpg",
    rating: 4.6,
  },
  {
    id: 8,
    name: "Business 8",
    location: "Odense",
    service: "Salon",
    imageUrl: "/salon.jpg",
    rating: 4.0,
  },
  {
    id: 9,
    name: "Business 9",
    location: "Kolding",
    service: "Massage",
    imageUrl: "/spa.jpg",
    rating: 3.7,
  },
  {
    id: 10,
    name: "Business 10",
    location: "Copenhagen",
    service: "Massage",
    imageUrl: "/spa.jpg",
    rating: 4.3,
  },
  {
    id: 10,
    name: "Business 11",
    location: "Odense",
    service: "Massage",
    imageUrl: "/spa.jpg",
    rating: 4.3,
  },
];

export default businessData;
